steps:
  - name: Check SSH key secret
    run: |
      if [ -z "${{ secrets.EC2_SSH_KEY }}" ]; then
        echo "EC2_SSH_KEY is EMPTY or NOT AVAILABLE"
        exit 1
      else
        echo "EC2_SSH_KEY is available"
      fi

  - name: Deploy to EC2
    uses: appleboy/ssh-action@v1.0.3
    with:
      host: ${{ secrets.EC2_HOST }}
      username: ${{ secrets.EC2_USERNAME }}
      key: ${{ secrets.EC2_SSH_KEY }}
